import { Post, Persona } from '../types';

export const INITIAL_PERSONAS: Record<string, Persona> = {
  cat_tama: {
    id: 'persona_cat_tama',
    name: 'Tama 🐱 萌芽日记',
    handle: '@tama_japanese_n0',
    avatarUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=150&auto=format&fit=crop&q=80',
    category: 'lifestyle',
    bioZh: 'N0 零基础伴学小猫 / 每天学一个假名与简单表达',
  },
  coffee_ken: {
    id: 'persona_coffee_ken',
    name: 'Ken | 咖啡研究员',
    handle: '@coffee_master_ken',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    category: 'coffee',
    bioZh: '东京浅草自烘焙咖啡店主理人 / 每日手冲分享',
  },
  tech_yuki: {
    id: 'persona_tech_yuki',
    name: 'Yuki 💻 TS魔改师',
    handle: '@dev_tokyo_yuki',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    category: 'tech',
    bioZh: '全栈架构师 / 开源爱好者 / TypeScript 狂热者',
  },
  soccer_ren: {
    id: 'persona_soccer_ren',
    name: 'Ren ⚽️ 战术推演',
    handle: '@tactics_tokyo_ren',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    category: 'sports',
    bioZh: 'J联赛观察员 / 海外组球员动态追踪',
  },
  food_mei: {
    id: 'persona_food_mei',
    name: 'Mei 🍣 美食探店',
    handle: '@tokyo_gourmet_mei',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    category: 'food',
    bioZh: '东京美食达人 / 居酒屋与拉面巡礼',
  },
  gaming_shin: {
    id: 'persona_gaming_shin',
    name: 'Shin 🎮 主机头号玩家',
    handle: '@game_stream_shin',
    avatarUrl: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
    category: 'gaming',
    bioZh: '任天堂与Steam游戏评测 / 每日速通挑战',
  },
};

export const INITIAL_SEED_POSTS: Post[] = [
  // ==========================================
  // 1. 🐱 日常生活与萌宠伴学 (Lifestyle & Cats)
  // ==========================================
  {
    id: 'post_life_01',
    persona: INITIAL_PERSONAS.cat_tama!,
    contentJa: 'あ！ねこ！可愛い！✨',
    translationZh: '啊！是猫咪！好可爱！✨',
    imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&auto=format&fit=crop&q=80',
    category: 'lifestyle',
    level: 'N0',
    likesCount: 520,
    repostsCount: 98,
    createdAt: '1m ago',
    tokens: [
      { id: 't_a', surface: 'あ', reading: 'あ', romaji: 'a', lemma: 'あ', pos: '感叹词', level: 'N0', definitionZh: '啊 (感叹声)', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_ex_a', surface: '！', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '感叹号' },
      { id: 't_neko', surface: 'ねこ', reading: 'ねこ', romaji: 'neko', lemma: '猫', pos: '名词', level: 'N0', definitionZh: '猫咪', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_ex_neko', surface: '！', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '感叹号' },
      { id: 't_kawaii', surface: '可愛い', reading: 'かわいい', romaji: 'kawaii', lemma: '可愛い', pos: '描述词', level: 'N0', definitionZh: '可爱', pitchAccent: { pattern: 'nakadaka', pitchNotation: '3' } },
      { id: 't_ex_kawaii', surface: '！✨', reading: '', romaji: '', lemma: '！✨', pos: '标点', level: 'N0', definitionZh: '表情' },
    ],
    comments: [],
  },
  {
    id: 'post_life_02_text',
    persona: INITIAL_PERSONAS.cat_tama!,
    contentJa: 'これ、なに？たのしい！(≧∇≦)',
    translationZh: '这个，是什么？好开心！',
    category: 'lifestyle',
    level: 'N0',
    likesCount: 290,
    repostsCount: 30,
    createdAt: '5m ago',
    tokens: [
      { id: 't_kore_6', surface: 'これ', reading: 'これ', romaji: 'kore', lemma: 'これ', pos: '代词', level: 'N0', definitionZh: '这个', pitchAccent: { pattern: 'heiban', pitchNotation: '0' } },
      { id: 't_comma_6', surface: '、', reading: '', romaji: '', lemma: '、', pos: '标点', level: 'N0', definitionZh: '逗号' },
      { id: 't_nani', surface: 'なに', reading: 'なに', romaji: 'nani', lemma: 'なに', pos: '疑问词', level: 'N0', definitionZh: '什么', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_ques_6', surface: '？', reading: '', romaji: '', lemma: '？', pos: '标点', level: 'N0', definitionZh: '问号' },
      { id: 't_tanoshii', surface: 'たのしい', reading: 'たのしい', romaji: 'tanoshii', lemma: 'たのしい', pos: '描述词', level: 'N0', definitionZh: '开心/有趣', pitchAccent: { pattern: 'nakadaka', pitchNotation: '3' } },
      { id: 't_ex_6', surface: '！(≧∇≦)', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '颜文字' },
    ],
    comments: [],
  },
  {
    id: 'post_life_03',
    persona: INITIAL_PERSONAS.cat_tama!,
    contentJa: 'おやすみ。またあした。🌙💤',
    translationZh: '晚安。明天见。',
    category: 'lifestyle',
    level: 'N0',
    likesCount: 640,
    repostsCount: 42,
    createdAt: '12m ago',
    tokens: [
      { id: 't_oyasumi', surface: 'おやすみ', reading: 'おやすみ', romaji: 'oyasumi', lemma: 'お休み', pos: '感叹词', level: 'N0', definitionZh: '晚安', pitchAccent: { pattern: 'heiban', pitchNotation: '0' } },
      { id: 't_period_o', surface: '。', reading: '', romaji: '', lemma: '。', pos: '标点', level: 'N0', definitionZh: '句号' },
      { id: 't_mata', surface: 'また', reading: 'また', romaji: 'mata', lemma: 'また', pos: '副词', level: 'N0', definitionZh: '再次/又', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_ashita', surface: 'あした', reading: 'あした', romaji: 'ashita', lemma: '明日', pos: '名词', level: 'N0', definitionZh: '明天', pitchAccent: { pattern: 'nakadaka', pitchNotation: '3' } },
      { id: 't_period_m', surface: '。🌙💤', reading: '', romaji: '', lemma: '。', pos: '标点', level: 'N0', definitionZh: '表情' },
    ],
    comments: [],
  },
  {
    id: 'post_life_04',
    persona: INITIAL_PERSONAS.cat_tama!,
    contentJa: 'いぬ！おおきい！すごい！🐶',
    translationZh: '是狗狗！好大一只！好厉害！🐶',
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
    category: 'lifestyle',
    level: 'N0',
    likesCount: 410,
    repostsCount: 35,
    createdAt: '22m ago',
    tokens: [
      { id: 't_inu', surface: 'いぬ', reading: 'いぬ', romaji: 'inu', lemma: '犬', pos: '名词', level: 'N0', definitionZh: '狗', pitchAccent: { pattern: 'nakadaka', pitchNotation: '2' } },
      { id: 't_ex_inu', surface: '！', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '感叹号' },
      { id: 't_ookii', surface: 'おおきい', reading: 'おおきい', romaji: 'ookii', lemma: '大きい', pos: '描述词', level: 'N0', definitionZh: '巨大的/大', pitchAccent: { pattern: 'nakadaka', pitchNotation: '3' } },
      { id: 't_ex_ookii', surface: '！', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '感叹号' },
      { id: 't_sugoi', surface: 'すごい', reading: 'すごい', romaji: 'sugoi', lemma: '凄い', pos: '描述词', level: 'N0', definitionZh: '厉害/棒', pitchAccent: { pattern: 'nakadaka', pitchNotation: '2' } },
      { id: 't_ex_sugoi', surface: '！🐶', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '表情' },
    ],
    comments: [],
  },
  {
    id: 'post_life_05_text',
    persona: INITIAL_PERSONAS.cat_tama!,
    contentJa: 'こんにちは！元気？( •̀ ω •́ )✧',
    translationZh: '你好！精神好吗？',
    category: 'lifestyle',
    level: 'N0',
    likesCount: 380,
    repostsCount: 22,
    createdAt: '35m ago',
    tokens: [
      { id: 't_konnichiwa', surface: 'こんにちは', reading: 'こんにちは', romaji: 'konnichiwa', lemma: 'こんにちは', pos: '感叹词', level: 'N0', definitionZh: '你好/白天问候', pitchAccent: { pattern: 'heiban', pitchNotation: '0' } },
      { id: 't_ex_kon', surface: '！', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '感叹号' },
      { id: 't_genki', surface: '元気', reading: 'げんき', romaji: 'genki', lemma: '元気', pos: '名词', level: 'N0', definitionZh: '精神/健康', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_ques_genki', surface: '？( •̀ ω •́ )✧', reading: '', romaji: '', lemma: '？', pos: '标点', level: 'N0', definitionZh: '表情' },
    ],
    comments: [],
  },

  // ==========================================
  // 2. ☕ 咖啡与生活美学 (Coffee & Cafe)
  // ==========================================
  {
    id: 'post_coffee_01_text',
    persona: INITIAL_PERSONAS.coffee_ken!,
    contentJa: 'おはよう！☕️ 今日もいい日！( •̀ ω •́ )✧',
    translationZh: '早安！☕️ 今天也是美好的一天！',
    category: 'coffee',
    level: 'N0',
    likesCount: 310,
    repostsCount: 45,
    createdAt: '3m ago',
    tokens: [
      { id: 't_ohayou', surface: 'おはよう', reading: 'おはよう', romaji: 'ohayou', lemma: 'おはよう', pos: '感叹词', level: 'N0', definitionZh: '早安/你好', pitchAccent: { pattern: 'nakadaka', pitchNotation: '2' } },
      { id: 't_ex_o', surface: '！☕️', reading: '', romaji: '', lemma: '！☕️', pos: '标点', level: 'N0', definitionZh: '表情' },
      { id: 't_kyou', surface: '今日', reading: 'きょう', romaji: 'kyou', lemma: '今日', pos: '名词', level: 'N0', definitionZh: '今天', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_mo', surface: 'も', reading: 'も', romaji: 'mo', lemma: 'も', pos: '助词', level: 'N0', definitionZh: '也', pitchAccent: { pattern: 'heiban', pitchNotation: '0' } },
      { id: 't_ii', surface: 'いい', reading: 'いい', romaji: 'ii', lemma: 'いい', pos: '描述词', level: 'N0', definitionZh: '好的/好', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_hi', surface: '日', reading: 'ひ', romaji: 'hi', lemma: '日', pos: '名词', level: 'N0', definitionZh: '日子', pitchAccent: { pattern: 'heiban', pitchNotation: '0' } },
      { id: 't_ex_hi', surface: '！', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '感叹号' },
    ],
    comments: [],
  },
  {
    id: 'post_coffee_02',
    persona: INITIAL_PERSONAS.coffee_ken!,
    contentJa: '朝の珈琲。いい香り。☕️✨',
    translationZh: '早晨的咖啡。香气宜人。',
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&auto=format&fit=crop&q=80',
    category: 'coffee',
    level: 'N0',
    likesCount: 510,
    repostsCount: 65,
    createdAt: '18m ago',
    tokens: [
      { id: 't_asa_c', surface: '朝', reading: 'あさ', romaji: 'asa', lemma: '朝', pos: '名词', level: 'N0', definitionZh: '早晨', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_no_c', surface: 'の', reading: 'の', romaji: 'no', lemma: 'の', pos: '助词', level: 'N0', definitionZh: '的', pitchAccent: { pattern: 'heiban', pitchNotation: '0' } },
      { id: 't_kouhii', surface: '珈琲', reading: 'コーヒー', romaji: 'koohii', lemma: '珈琲', pos: '名词', level: 'N0', definitionZh: '咖啡', pitchAccent: { pattern: 'nakadaka', pitchNotation: '3' } },
      { id: 't_period_c', surface: '。', reading: '', romaji: '', lemma: '。', pos: '标点', level: 'N0', definitionZh: '句号' },
      { id: 't_ii_c', surface: 'いい', reading: 'いい', romaji: 'ii', lemma: 'いい', pos: '描述词', level: 'N0', definitionZh: '好的', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_kaori', surface: '香り', reading: 'かおり', romaji: 'kaori', lemma: '香り', pos: '名词', level: 'N0', definitionZh: '香气/芳香', pitchAccent: { pattern: 'heiban', pitchNotation: '0' } },
      { id: 't_period_k', surface: '。☕️✨', reading: '', romaji: '', lemma: '。', pos: '标点', level: 'N0', definitionZh: '表情' },
    ],
    comments: [],
  },
  {
    id: 'post_coffee_03_text',
    persona: INITIAL_PERSONAS.coffee_ken!,
    contentJa: '水！つめたい！おいしい！💧',
    translationZh: '水！冰冰凉凉！好喝！',
    category: 'coffee',
    level: 'N0',
    likesCount: 220,
    repostsCount: 15,
    createdAt: '28m ago',
    tokens: [
      { id: 't_mizu', surface: '水', reading: 'みず', romaji: 'mizu', lemma: '水', pos: '名词', level: 'N0', definitionZh: '水', pitchAccent: { pattern: 'heiban', pitchNotation: '0' } },
      { id: 't_ex_mizu', surface: '！', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '感叹号' },
      { id: 't_tsumetai', surface: 'つめたい', reading: 'つめたい', romaji: 'tsumetai', lemma: '冷たい', pos: '描述词', level: 'N0', definitionZh: '冰凉的/冷', pitchAccent: { pattern: 'heiban', pitchNotation: '0' } },
      { id: 't_ex_tsu', surface: '！', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '感叹号' },
      { id: 't_oishii_w', surface: 'おいしい', reading: 'おいしい', romaji: 'oishii', lemma: '美味しい', pos: '描述词', level: 'N0', definitionZh: '好喝/美味', pitchAccent: { pattern: 'nakadaka', pitchNotation: '3' } },
      { id: 't_ex_oi_w', surface: '！💧', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '表情' },
    ],
    comments: [],
  },
  {
    id: 'post_coffee_04',
    persona: INITIAL_PERSONAS.coffee_ken!,
    contentJa: 'カフェで本を読む。静か。📖',
    translationZh: '在咖啡店看书。很安静。',
    imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600&auto=format&fit=crop&q=80',
    category: 'coffee',
    level: 'N5',
    likesCount: 460,
    repostsCount: 52,
    createdAt: '42m ago',
    tokens: [
      { id: 't_kafe', surface: 'カフェ', reading: 'カフェ', romaji: 'kafe', lemma: 'カフェ', pos: '名词', level: 'N5', definitionZh: '咖啡店', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_de', surface: 'で', reading: 'で', romaji: 'de', lemma: 'で', pos: '助词', level: 'N5', definitionZh: '在 (场所)', pitchAccent: { pattern: 'heiban', pitchNotation: '0' } },
      { id: 't_hon', surface: '本', reading: 'ほん', romaji: 'hon', lemma: '本', pos: '名词', level: 'N5', definitionZh: '书本', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_wo', surface: 'を', reading: 'を', romaji: 'wo', lemma: 'を', pos: '助词', level: 'N5', definitionZh: '动作对象', pitchAccent: { pattern: 'heiban', pitchNotation: '0' } },
      { id: 't_yomu', surface: '読む', reading: 'よむ', romaji: 'yomu', lemma: '読む', pos: '动作词', level: 'N5', definitionZh: '阅读', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_period_y', surface: '。', reading: '', romaji: '', lemma: '。', pos: '标点', level: 'N5', definitionZh: '句号' },
      { id: 't_shizuka', surface: '静か', reading: 'しずか', romaji: 'shizuka', lemma: '静か', pos: '描述词', level: 'N5', definitionZh: '安静', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_period_s', surface: '。📖', reading: '', romaji: '', lemma: '。', pos: '标点', level: 'N5', definitionZh: '表情' },
    ],
    comments: [],
  },

  // ==========================================
  // 3. 🍣 美食料理与探店 (Food & Izakaya)
  // ==========================================
  {
    id: 'post_food_01',
    persona: INITIAL_PERSONAS.food_mei!,
    contentJa: '寿司！おいしい！ありがとう！🍣',
    translationZh: '寿司！好吃！谢谢！🍣',
    imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&auto=format&fit=crop&q=80',
    category: 'food',
    level: 'N0',
    likesCount: 680,
    repostsCount: 120,
    createdAt: '8m ago',
    tokens: [
      { id: 't_sushi', surface: '寿司', reading: 'すし', romaji: 'sushi', lemma: '寿司', pos: '名词', level: 'N0', definitionZh: '寿司', pitchAccent: { pattern: 'heiban', pitchNotation: '2' } },
      { id: 't_ex_sushi', surface: '！', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '感叹号' },
      { id: 't_oishii', surface: 'おいしい', reading: 'おいしい', romaji: 'oishii', lemma: 'おいしい', pos: '描述词', level: 'N0', definitionZh: '美味/好吃', pitchAccent: { pattern: 'nakadaka', pitchNotation: '3' } },
      { id: 't_ex_oishii', surface: '！', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '感叹号' },
      { id: 't_arigatou', surface: 'ありがとう', reading: 'ありがとう', romaji: 'arigatou', lemma: 'ありがとう', pos: '感叹词', level: 'N0', definitionZh: '谢谢', pitchAccent: { pattern: 'nakadaka', pitchNotation: '2' } },
      { id: 't_ex_ari', surface: '！🍣', reading: '', romaji: '', lemma: '！🍣', pos: '标点', level: 'N0', definitionZh: '表情' },
    ],
    comments: [],
  },
  {
    id: 'post_food_02',
    persona: INITIAL_PERSONAS.food_mei!,
    contentJa: 'ラーメン！熱い！うまい！🍜',
    translationZh: '拉面！热气腾腾！好香！🍜',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop&q=80',
    category: 'food',
    level: 'N0',
    likesCount: 840,
    repostsCount: 160,
    createdAt: '16m ago',
    tokens: [
      { id: 't_raamen', surface: 'ラーメン', reading: 'ラーメン', romaji: 'raamen', lemma: 'ラーメン', pos: '名词', level: 'N0', definitionZh: '拉面', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_ex_raa', surface: '！', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '感叹号' },
      { id: 't_atsui', surface: '熱い', reading: 'あつい', romaji: 'atsui', lemma: '熱い', pos: '描述词', level: 'N0', definitionZh: '烫的/热', pitchAccent: { pattern: 'nakadaka', pitchNotation: '2' } },
      { id: 't_ex_atsui', surface: '！', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '感叹号' },
      { id: 't_umai', surface: 'うまい', reading: 'うまい', romaji: 'umai', lemma: 'うまい', pos: '描述词', level: 'N0', definitionZh: '美味/好吃', pitchAccent: { pattern: 'nakadaka', pitchNotation: '2' } },
      { id: 't_ex_umai', surface: '！🍜', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '表情' },
    ],
    comments: [],
  },
  {
    id: 'post_food_03_text',
    persona: INITIAL_PERSONAS.food_mei!,
    contentJa: 'おなかすいた！ご飯食べよう！🍚🥢',
    translationZh: '肚子饿了！去吃饭吧！',
    category: 'food',
    level: 'N0',
    likesCount: 390,
    repostsCount: 40,
    createdAt: '30m ago',
    tokens: [
      { id: 't_onaka', surface: 'おなか', reading: 'おなか', romaji: 'onaka', lemma: 'お腹', pos: '名词', level: 'N0', definitionZh: '肚子', pitchAccent: { pattern: 'heiban', pitchNotation: '0' } },
      { id: 't_suita', surface: 'すいた', reading: 'すいた', romaji: 'suita', lemma: '空く', pos: '描述词', level: 'N0', definitionZh: '空了/饿了', pitchAccent: { pattern: 'nakadaka', pitchNotation: '2' } },
      { id: 't_ex_ona', surface: '！', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '感叹号' },
      { id: 't_gohan', surface: 'ご飯', reading: 'ごはん', romaji: 'gohan', lemma: 'ご飯', pos: '名词', level: 'N0', definitionZh: '饭/餐', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_tabeyou', surface: '食べよう', reading: 'たべよう', romaji: 'tabeyou', lemma: '食べる', pos: '动作词', level: 'N0', definitionZh: '吃吧 (提议)', pitchAccent: { pattern: 'nakadaka', pitchNotation: '3' } },
      { id: 't_ex_tabe', surface: '！🍚🥢', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '表情' },
    ],
    comments: [],
  },
  {
    id: 'post_food_04',
    persona: INITIAL_PERSONAS.food_mei!,
    contentJa: '抹茶アイス。甘くて冷たい。🍦🍵',
    translationZh: '抹茶冰淇淋。又甜又冰。',
    imageUrl: 'https://images.unsplash.com/photo-1505394033641-40c6ad1178d7?w=600&auto=format&fit=crop&q=80',
    category: 'food',
    level: 'N5',
    likesCount: 570,
    repostsCount: 88,
    createdAt: '50m ago',
    tokens: [
      { id: 't_matcha', surface: '抹茶', reading: 'まっちゃ', romaji: 'matcha', lemma: '抹茶', pos: '名词', level: 'N5', definitionZh: '抹茶', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_aisu', surface: 'アイス', reading: 'アイス', romaji: 'aisu', lemma: 'アイス', pos: '名词', level: 'N5', definitionZh: '冰淇淋', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_period_ai', surface: '。', reading: '', romaji: '', lemma: '。', pos: '标点', level: 'N5', definitionZh: '句号' },
      { id: 't_amakute', surface: '甘くて', reading: 'あまくて', romaji: 'amakute', lemma: '甘い', pos: '描述词', level: 'N5', definitionZh: '甜的 (连接型)', pitchAccent: { pattern: 'nakadaka', pitchNotation: '2' } },
      { id: 't_tsume_5', surface: '冷たい', reading: 'つめたい', romaji: 'tsumetai', lemma: '冷たい', pos: '描述词', level: 'N5', definitionZh: '冰凉的', pitchAccent: { pattern: 'heiban', pitchNotation: '0' } },
      { id: 't_period_tsu', surface: '。🍦🍵', reading: '', romaji: '', lemma: '。', pos: '标点', level: 'N5', definitionZh: '表情' },
    ],
    comments: [],
  },

  // ==========================================
  // 4. 💻 科技开发与极客 (Tech & Coding)
  // ==========================================
  {
    id: 'post_tech_01_text',
    persona: INITIAL_PERSONAS.tech_yuki!,
    contentJa: 'はい！OK！バグなし！🎉💪',
    translationZh: '好的！OK！没有Bug！🎉💪',
    category: 'tech',
    level: 'N0',
    likesCount: 450,
    repostsCount: 88,
    createdAt: '15m ago',
    tokens: [
      { id: 't_hai', surface: 'はい', reading: 'はい', romaji: 'hai', lemma: 'はい', pos: '感叹词', level: 'N0', definitionZh: '好的/是的', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_ex_hai', surface: '！', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '感叹号' },
      { id: 't_ok', surface: 'OK', reading: 'オーケー', romaji: 'ookee', lemma: 'OK', pos: '感叹词', level: 'N0', definitionZh: '没问题', pitchAccent: { pattern: 'heiban', pitchNotation: '0' } },
      { id: 't_ex_ok', surface: '！', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '感叹号' },
      { id: 't_bagu', surface: 'バグ', reading: 'バグ', romaji: 'bagu', lemma: 'バグ', pos: '名词', level: 'N0', definitionZh: 'Bug/程序缺陷', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_nashi', surface: 'なし', reading: 'なし', romaji: 'nashi', lemma: 'なし', pos: '描述词', level: 'N0', definitionZh: '没有/无', pitchAccent: { pattern: 'heiban', pitchNotation: '0' } },
      { id: 't_ex_bagu', surface: '！🎉💪', reading: '', romaji: '', lemma: '！🎉💪', pos: '标点', level: 'N0', definitionZh: '表情' },
    ],
    comments: [],
  },
  {
    id: 'post_tech_02_text',
    persona: INITIAL_PERSONAS.tech_yuki!,
    contentJa: 'コードを書く。動いた！うれしい！💻⚡️',
    translationZh: '写代码。跑通了！好开心！',
    category: 'tech',
    level: 'N0',
    likesCount: 380,
    repostsCount: 70,
    createdAt: '24m ago',
    tokens: [
      { id: 't_koodo', surface: 'コード', reading: 'コード', romaji: 'koodo', lemma: 'コード', pos: '名词', level: 'N0', definitionZh: '代码', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_wo_t', surface: 'を', reading: 'を', romaji: 'wo', lemma: 'を', pos: '助词', level: 'N0', definitionZh: '动作对象', pitchAccent: { pattern: 'heiban', pitchNotation: '0' } },
      { id: 't_kaku', surface: '書く', reading: 'かく', romaji: 'kaku', lemma: '書く', pos: '动作词', level: 'N0', definitionZh: '写', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_period_kaku', surface: '。', reading: '', romaji: '', lemma: '。', pos: '标点', level: 'N0', definitionZh: '句号' },
      { id: 't_ugoita', surface: '動いた', reading: 'うごいた', romaji: 'ugoita', lemma: '動く', pos: '动作词', level: 'N0', definitionZh: '动起来了/运行了', pitchAccent: { pattern: 'nakadaka', pitchNotation: '2' } },
      { id: 't_ex_ugoi', surface: '！', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '感叹号' },
      { id: 't_ureshii', surface: 'うれしい', reading: 'うれしい', romaji: 'ureshii', lemma: '嬉しい', pos: '描述词', level: 'N0', definitionZh: '开心的/高兴', pitchAccent: { pattern: 'nakadaka', pitchNotation: '3' } },
      { id: 't_ex_ure', surface: '！💻⚡️', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '表情' },
    ],
    comments: [],
  },
  {
    id: 'post_tech_03',
    persona: INITIAL_PERSONAS.tech_yuki!,
    contentJa: '新しいパソコン。とても速い！🚀',
    translationZh: '新电脑。速度超级快！',
    imageUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&auto=format&fit=crop&q=80',
    category: 'tech',
    level: 'N5',
    likesCount: 620,
    repostsCount: 95,
    createdAt: '48m ago',
    tokens: [
      { id: 't_atarashii', surface: '新しい', reading: 'あたらしい', romaji: 'atarashii', lemma: '新しい', pos: '描述词', level: 'N5', definitionZh: '新的', pitchAccent: { pattern: 'nakadaka', pitchNotation: '4' } },
      { id: 't_pasokon', surface: 'パソコン', reading: 'パソコン', romaji: 'pasokon', lemma: 'パソコン', pos: '名词', level: 'N5', definitionZh: '电脑/PC', pitchAccent: { pattern: 'heiban', pitchNotation: '0' } },
      { id: 't_period_p', surface: '。', reading: '', romaji: '', lemma: '。', pos: '标点', level: 'N5', definitionZh: '句号' },
      { id: 't_totemo', surface: 'とても', reading: 'とても', romaji: 'totemo', lemma: 'とても', pos: '副词', level: 'N5', definitionZh: '非常', pitchAccent: { pattern: 'heiban', pitchNotation: '0' } },
      { id: 't_hayai', surface: '速い', reading: 'はやい', romaji: 'hayai', lemma: '速い', pos: '描述词', level: 'N5', definitionZh: '快的', pitchAccent: { pattern: 'nakadaka', pitchNotation: '2' } },
      { id: 't_ex_hayai', surface: '！🚀', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N5', definitionZh: '表情' },
    ],
    comments: [],
  },

  // ==========================================
  // 5. ⚽ 体育运动与健身 (Sports & Fitness)
  // ==========================================
  {
    id: 'post_sports_01',
    persona: INITIAL_PERSONAS.soccer_ren!,
    contentJa: 'ゴール！勝った！最高！⚽️🔥',
    translationZh: '进球！赢了！最棒！⚽️🔥',
    imageUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=600&auto=format&fit=crop&q=80',
    category: 'sports',
    level: 'N0',
    likesCount: 920,
    repostsCount: 310,
    createdAt: '20m ago',
    tokens: [
      { id: 't_gooru', surface: 'ゴール', reading: 'ゴール', romaji: 'gooru', lemma: 'ゴール', pos: '名词', level: 'N0', definitionZh: '进球/得分', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_ex_gooru', surface: '！', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '感叹号' },
      { id: 't_katta', surface: '勝った', reading: 'かった', romaji: 'katta', lemma: '胜つ', pos: '动作词', level: 'N0', definitionZh: '赢了(过去时)', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_ex_katta', surface: '！', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '感叹号' },
      { id: 't_saikou_n0', surface: '最高', reading: 'さいこう', romaji: 'saikou', lemma: '最高', pos: '描述词', level: 'N0', definitionZh: '最棒/最高', pitchAccent: { pattern: 'heiban', pitchNotation: '0' } },
      { id: 't_ex_saikou', surface: '！⚽️🔥', reading: '', romaji: '', lemma: '！⚽️🔥', pos: '标点', level: 'N0', definitionZh: '表情' },
    ],
    comments: [],
  },
  {
    id: 'post_sports_02_text',
    persona: INITIAL_PERSONAS.soccer_ren!,
    contentJa: '走る！疲れた！でも気持ちいい！🏃‍♂️💨',
    translationZh: '跑步！累了！但很爽快！',
    category: 'sports',
    level: 'N0',
    likesCount: 350,
    repostsCount: 28,
    createdAt: '38m ago',
    tokens: [
      { id: 't_hashiru', surface: '走る', reading: 'はしる', romaji: 'hashiru', lemma: '走る', pos: '动作词', level: 'N0', definitionZh: '跑/跑步', pitchAccent: { pattern: 'nakadaka', pitchNotation: '2' } },
      { id: 't_ex_hashi', surface: '！', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '感叹号' },
      { id: 't_tsukareta', surface: '疲れた', reading: 'つかれた', romaji: 'tsukareta', lemma: '疲れる', pos: '动作词', level: 'N0', definitionZh: '累了', pitchAccent: { pattern: 'nakadaka', pitchNotation: '3' } },
      { id: 't_ex_tsuka', surface: '！', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '感叹号' },
      { id: 't_demo', surface: 'でも', reading: 'でも', romaji: 'demo', lemma: 'でも', pos: '连词', level: 'N0', definitionZh: '但是', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_kimochiii', surface: '気持ちいい', reading: 'きもちいい', romaji: 'kimochiii', lemma: '気持ちいい', pos: '描述词', level: 'N0', definitionZh: '感觉舒爽/痛快', pitchAccent: { pattern: 'nakadaka', pitchNotation: '4' } },
      { id: 't_ex_kimo', surface: '！🏃‍♂️💨', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '表情' },
    ],
    comments: [],
  },

  // ==========================================
  // 6. 🎮 动漫与主机游戏 (Gaming & Anime)
  // ==========================================
  {
    id: 'post_game_01',
    persona: INITIAL_PERSONAS.gaming_shin!,
    contentJa: 'ゲームクリア！やったー！🎉🏆',
    translationZh: '游戏通关！太棒啦！🎉🏆',
    imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80',
    category: 'gaming',
    level: 'N0',
    likesCount: 780,
    repostsCount: 140,
    createdAt: '10m ago',
    tokens: [
      { id: 't_geemu', surface: 'ゲーム', reading: 'ゲーム', romaji: 'geemu', lemma: 'ゲーム', pos: '名词', level: 'N0', definitionZh: '游戏', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_kuria', surface: 'クリア', reading: 'クリア', romaji: 'kuria', lemma: 'クリア', pos: '名词', level: 'N0', definitionZh: '通关/Clear', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_ex_kuri', surface: '！', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '感叹号' },
      { id: 't_yattaa', surface: 'やったー', reading: 'やったー', romaji: 'yattaa', lemma: 'やったー', pos: '感叹词', level: 'N0', definitionZh: '太好啦/搞定啦', pitchAccent: { pattern: 'nakadaka', pitchNotation: '3' } },
      { id: 't_ex_yatta', surface: '！🎉🏆', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '表情' },
    ],
    comments: [],
  },
  {
    id: 'post_game_02_text',
    persona: INITIAL_PERSONAS.gaming_shin!,
    contentJa: '強い敵！負けた！もう一回！🔥🎮',
    translationZh: '好强的敌人！输了！再来一次！',
    category: 'gaming',
    level: 'N0',
    likesCount: 520,
    repostsCount: 60,
    createdAt: '32m ago',
    tokens: [
      { id: 't_tsuyoi', surface: '強い', reading: 'つよい', romaji: 'tsuyoi', lemma: '強い', pos: '描述词', level: 'N0', definitionZh: '强大的/强', pitchAccent: { pattern: 'nakadaka', pitchNotation: '2' } },
      { id: 't_teki', surface: '敵', reading: 'てき', romaji: 'teki', lemma: '敵', pos: '名词', level: 'N0', definitionZh: '敌人', pitchAccent: { pattern: 'heiban', pitchNotation: '0' } },
      { id: 't_ex_teki', surface: '！', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '感叹号' },
      { id: 't_maketa', surface: '負けた', reading: 'まけた', romaji: 'maketa', lemma: '負ける', pos: '动作词', level: 'N0', definitionZh: '输了', pitchAccent: { pattern: 'heiban', pitchNotation: '0' } },
      { id: 't_ex_make', surface: '！', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '感叹号' },
      { id: 't_mou', surface: 'もう', reading: 'もう', romaji: 'mou', lemma: 'もう', pos: '副词', level: 'N0', definitionZh: '再', pitchAccent: { pattern: 'atamadaka', pitchNotation: '1' } },
      { id: 't_ikkai', surface: '一回', reading: 'いっかい', romaji: 'ikkai', lemma: '一回', pos: '名词', level: 'N0', definitionZh: '一次', pitchAccent: { pattern: 'heiban', pitchNotation: '0' } },
      { id: 't_ex_ikkai', surface: '！🔥🎮', reading: '', romaji: '', lemma: '！', pos: '标点', level: 'N0', definitionZh: '表情' },
    ],
    comments: [],
  },
];
